# steps:   
#   #Run Software Composition Analysis (SCA security scan) using Snyk
#   - name: maven:3-openjdk-18-slim
#     entrypoint: mvn
#     args: ['verify', 'sonar:sonar','-Dsonar.host.url=https://sonarcloud.io','-Dsonar.organization=gcpsourcecodereposcan','-Dsonar.projectKey=gcpvulnerableprojectkey','-Dsonar.token=${_SONAR_TOKEN}']
  
#   - name: 'ubuntu'
#     entrypoint: bash
#     args: 
#         - '-c'
#         - |-
#           apt-get update
#           apt-get -y install maven 
#           SNYK_TOKEN=${_SNYK_TOKEN}
#           export SNYK_TOKEN
#           mvn snyk:test -fn 
#     id: Snyk SCA

# options:
#   logging: CLOUD_LOGGING_ONLY

steps:   
#Run DAST scan using OWASP ZAP in GCP DevSecOps Pipeline
  - name: 'ubuntu'
    entrypoint: bash
    args: 
      - '-c'
      - |-
        apt-get update
        apt-get -y install wget
        apt-get -y install default-jdk
        wget https://github.com/zaproxy/zaproxy/releases/download/v2.16.0/ZAP_2.16.0_Linux.tar.gz
        tar -xvf ZAP_2.16.0_Linux.tar.gz
        cd ZAP_2.16.0
        ./zap.sh -cmd -quickurl https://historia.samudera.id -quickprogress -quickout ../zap_report.html 
    id: DAST Scan using OWASP ZAP
artifacts:
  objects:
    location: 'gs://dast-integration'
    paths:
      - zap_report.html

options:
  logging: CLOUD_LOGGING_ONLY
 